app = "system-rival"
primary_region = "iad"

[build]
<<<<<<< HEAD
  dockerfile = "Dockerfile"
=======
  # لا تقم بتغيير هذا الجزء، سيقوم Fly.io بالتعرف على Python تلقائياً
>>>>>>> 8668f4f59c71995fd055ee346020fdb4722513e8

[env]
  PORT = "5000"
  FLASK_APP = "system_app.app:app"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "15s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# هذا الجزء هو الأهم لإخبار Fly.io كيف يشغل تطبيقك
[processes]
  app = "gunicorn --bind 0.0.0.0:5000 app:app"
